### ISSUE TITLE
No need to refund if ETH required is already funded

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden-wizard#152]
If 0.175 ETH are funded we can skip funding eth to the address or make it optional

**Comment by agatsoh** [comment]
@fredo @Dominik1999 
The code to skip funding ETH and redirecting to the token swaps is already there [here](https://github.com/raiden-network/raiden-wizard/blob/master/resources/templates/account.html#L129-L138). inside the poll function. which calls the [hasEnoughBalanceToLaunchRaiden](https://github.com/raiden-network/raiden-wizard/blob/master/resources/templates/base.html#L103-L107) function which also has the correct logic, which means only when you dont have enough tokens only then you would be required to fund with ETH otherwise ether amount higher than `0.1 ETH` which is the `ETHEREUM_REQUIRED_AMOUNT_AFTER_SWAP` is allowed to pass. 

What probably might be required be required is to reduce the poll time and redirect him to the launch raiden page if it already satisfies the token amounts

**Comment by Dominik1999** [comment]
If I understood @manuelwedler correctly he already implemented that. Can you check and test that @agatsoh ?

If it is already there and works as expected, can you write a test for that @agatsoh ?

**Comment by manuelwedler** [comment]
I already implemented that but it had that bug that it only would redirect if it also has enough tokens. 
So I created a fix today: https://github.com/raiden-network/raiden-wizard/pull/163

**Comment by agatsoh** [comment]
@Dominik1999 So we decided that @manuelwedler  will implement the following in the PR
If the user is falling short of `0.175 ETH` then he will refund his account with the difference of ETH and will redirect the `RDN` swap page. Irregardless of whether he has raiden tokens. Next time we can keep a skip button.

**Comment by Dominik1999** [comment]
Can you @agatsoh start writing a test for that in https://github.com/raiden-network/raiden-wizard/tree/master/tests
