### ISSUE TITLE
How much ETH should the Wizard require? 

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden-wizard#205]
This is an issue to discuss how much ETH should be required to run the wizard. 

Currently we ask for the upper bound assuming Closing 4 channels and buyin the maximum amount of RDN and DAI which leads to `0.18 ETH` which is quite a high entry barrier. 

To lower this amount, we could have some options: 

- Do not assume that the user will have 4 channels
- Only allow to buy a fixed amount of RDN and DAI (Maybe only in the first run. later the user could top up as he wishes)

IMHO in would be okay to not calculate costs for closing the channels in as the user can top up later at any time. This could even be done in the WebUI. Also the wizard on further runs (2nd 3rd and so on) could check for open channels and compare the current eth balance against what would be needed to close all channels he has. All in all topping up ETH is not big of a deal since this can happen while Raiden is running. 

In the first run we could also go with low amounts of RDN and DAI to provide a low entry barrier. Once the user likes using raiden we could give him the opportunity to exchange more (or even variable amounts) in further runs of the wizard. 

Example: 
10 RDN ~ 0.00565 ETH
5 DAI ~ 0.02578 ETH
2 USD ~ 0.010602 ETH transaction fee

Total: 0.042032 ETH
This would end up in ~ 0.05 ETH. @Dominik1999 What is you opinion here?

**Comment by fredo** [comment]
Due to price fluctuation we could also calculate transaction costs for the DAI and RDN swap on the spot and make the ETH price variable

**Comment by Dominik1999** [comment]
Thanks @fredo !

We should definitively decrease that amount. We also discussed that in our Biz Dev Meeting together with @czepluch and Luis (can't find GH name?).

We might come up with more convenient numbers by minimizing all three factors - channels to be opened, RDN needed and DAI needed

- **Channels:** We need to hold ~0.025 ETH for every channel we want to open. Raiden does not allow us to open a channel otherwise. <Insert code from Raiden Repo that calculates that, seems pretty high>

- **RDN:** We should not let the user chose how many RDN she will swap. 10 is a good number if we expect the user not to use a Monitoring Service. (with 2 DAI in the channel that might not be needed)

- **DAI:** We can even go for for a lower amount of DAI.

**Comment by Dominik1999** [comment]
We decided to have 0.11 ETH for the user and fixed amounts to swap 10 RDN and 3 DAI

```
Channel         0.075 ETH
10 Raiden T   0.00565 ETH
5 DAI             0.015468 ETH
2 $ for            0.01
```

**Comment by Dominik1999** [comment]
@fredo can you specify the necessary changes in back- and frontend and create issues?
